# Generated by Django 3.1.7 on 2021-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('salrey', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
